### ISSUE TITLE
Move to SpikeInterface?

### ISSUE THREAD

**Issue by bendichter** [SpikeInterface/MEArec#144]
We might want to officially consider this library part of the SpikeInterface suite. Thoughts?

**Comment by samuelgarcia** [comment]
This would require lot of works.

Mainly mearec is 2 big parts + read/write:
  1. simulate template using neuron+LFpy
  2. signal generation : convolution + noise

The part 2 could be quite easily ported to spikeinetrface (and it is partilally already done).
The part 1 is quite big + specific + strong dependency. So having outiside spikeinterface is wiser I think.

When more time I would be to continue pushing part in spikeinetrface.

**Comment by bendichter** [comment]
Sorry, I was unclear. I meant the SpikeInterface org, not the SpikeInterface repo

**Comment by samuelgarcia** [comment]
I made the shortcut "Move to SpikeINterface" = move code logic inside spikeinertface module
But you meant "Move to SpikeINterface" = transfert the repo to the SpikeInterface organisation I read it too quickly

**Comment by alejoe91** [comment]
Hi guys, I'm in favor of moving to the SI org :)

**Comment by bendichter** [comment]
ok great @alejoe91 I think you might be the only one who can do that

**Comment by alejoe91** [comment]
And done: https://github.com/SpikeInterface/MEArec
