### ISSUE TITLE
Bursting spikes code

### ISSUE THREAD

**Issue by ZiadAli** [SpikeInterface/MEArec#155]
Hello - in line 451 of the recordinggenerator.py file, shouldn’t the params key be “n_burst_spikes”, not “exp_decay”?
![3DB70193-E6D7-44E0-81B1-35E92A7D4140](https://github.com/SpikeInterface/MEArec/assets/14086156/05d44c74-6626-4476-aafa-253935147870)

**Comment by alejoe91** [comment]
Indeed! It's fixed here #156 

Note that normally this is never a problem since the `n_burst_spikes` is defined in the default parameters. The only way that one could "reach" the bug is to provide a custom dictionary made from scratch without that parameter, or to manually delete it ;)
